### ISSUE TITLE
Discoverability

### ISSUE THREAD

**Issue by samoconnor** [yuyichao/LibArchive.jl#1]
Please edit the GitHub project description (currently "Wrapper for libarchive") to be something like: "Wrapper for libarchive (gz, gzip, tar, pax, cpio, zip, xar, lha, ar, cab, mtree, rar, ISO)".

The GitHub project description shows up here : http://pkg.julialang.org and makes it easier to discover that this package knows about zip, tar, etc...

**Comment by yuyichao** [comment]
Sure and done. Thx.

**Comment by samoconnor** [comment]
nice one. thx
