### ISSUE TITLE
Uncompress a LZMA file and get a IOStream

### ISSUE THREAD

**Issue by femtotrader** [yuyichao/LibArchive.jl#2]
Hello,

this file http://www.dukascopy.com/datafeed/EURUSD/2016/02/14/20h_ticks.bi5
is a LZMA compressed file.

I'd like to be able to uncompress it using Julia
see https://github.com/femtotrader/DataReaders.jl/issues/14

I would like to have a IOStream of uncompressed file

According https://groups.google.com/forum/#!topic/julia-users/G9Pqe5svS3c 
LibArchive.jl could help to achieve this task

``` julia
fh = open("20h_ticks.bi5")
...
```

Any help will be nice.

Kind regards

**Comment by yuyichao** [comment]
Please keep questions on the mailing list.

``` jl
LibArchive.Reader("20h_ticks.bi5") do reader
    LibArchive.support_format_raw(reader)
    LibArchive.support_filter_all(reader)
    entry = LibArchive.next_header(reader)
    read(reader)
end
```

**Comment by femtotrader** [comment]
where is this mailing list ?

This should be in https://github.com/yuyichao/LibArchive.jl/blob/master/README.md

**Comment by yuyichao** [comment]
julia-users

**Comment by femtotrader** [comment]
Ok thanks.

I'm getting

```
80160-element Array{UInt8,1}:
 0x00
 0x00
 0x00
 0x25
 0x00
 0x01
 0xb1
 0x81
 0x00
 0x01
 0xb1
 0x80
 0x3f
 0x99
 0x99
 0x9a
 0x3f
 0xc0
 0x00
 0x00
    ⋮
 0x36
 0xe0
 0xad
 0x00
 0x01
 0xb1
 0xc0
 0x00
 0x01
 0xb1
 0xaa
 0x3f
 0x40
 0x00
 0x00
 0x3f
 0x40
 0x00
 0x00
```

Isn't there a way to get a `IOStream` ?

**Comment by yuyichao** [comment]
No. The IO interface is already as close to a IO as possible but it won't (and can't) be a `IOStream`.

**Comment by femtotrader** [comment]
Uhmm... seems difficult to plug it with my code.

``` julia
reader = LibArchive.Reader("20h_ticks.bi5")
LibArchive.support_format_raw(reader)
LibArchive.support_filter_all(reader)
entry = LibArchive.next_header(reader)
arr = read(reader)
... # create a stream from array of bytes
close(reader)
```

Any suggestion ?

**Comment by yuyichao** [comment]
You shouldn't be requiring `IOStream`.

**Comment by xiuliren** [comment]
you can use julia `pipeline` to do it. `lzma` command is available in most of linux os.

**Comment by femtotrader** [comment]
I'm requiring now `IO` instead of `IOStream`...
It works fine (see https://github.com/femtotrader/DukascopyTicksReader.jl )
but thanks @jingpengwu for this tip
